Sundsvallskommun/web-shared-components

- packages/modal/src/modal/modal.tsx
"as" on contentwrapper,
"as" on label,
hidelabel to still be able to use label on close button aria. 
spread rest
> Better modal heading and wrapper

- packages/core/src/components/pagination.js
- packages/core/src/components/zebratable.js
- packages/pagination/src/pagination.tsx
- packages/pagination/src/styles.ts
- packages/table/src/styles.ts
- packages/table/src/zebratable-header.tsx
- packages/table/src/zebratable.tsx
Added page sizes.
Fixed small bug on pagination, that caused "1" to be rendered twice when only one page exists.
Updated classnames on table and pagination.
Changed name on comments dataobject (error on build caused by 2 interfaces with the same name)
> Added page sizes on tables

- packages/checkbox/src/checkbox.tsx
- packages/core/src/components/checkbox.js
- packages/core/src/components/dropdown-filter.js
- packages/dropdown-filter/src/filter-item.tsx
- Added support for checkbox label left/right
- Moved item.name to Checkbox children-prop
> Adjusted from label within label to use checkbox props instead

- packages/forms/src/form-control/index.tsx
- packages/forms/src/form-label/index.tsx
- packages/forms/src/input/input.tsx
- packages/forms/src/select/index.tsx
- packages/forms/src/textarea/index.tsx
added fieldset support in formcontrol and formlabel (as legend) added support in select
added auto describedby
> form control update

- packages/accordion/stories/accordion.stories.tsx
BREAKING CHANGE: Old accordion is now called disclosure. The new accordion is a list of disclosures with some additional features.
> feat: new accordion

- packages/tabs/src/tabs.tsx
as initial focus should be decided by the app using the component I removed it.
> removed initial focus

- packages/side-menu/src/draggable.ts
- packages/side-menu/src/side-menu.tsx
removed unused menuId, fix for dragndrop not working, now takes menuitem class on constructor to make it explicit
> Fix for dragndrop not working

- packages/comments/src/comment-itemcontextmenu.tsx
- packages/comments/src/comments.tsx
- packages/comments/stories/commentsData.json
- packages/context-menu/src/context-menu.tsx
height full - y overflow fix
function execution from contextmenu
> Fixes comments and ContextMenu

- packages/core/src/base.js
- packages/core/src/components/button.js
- packages/core/src/components/header.js
- packages/core/src/components/popup-menu.js
- packages/core/src/components/user-menu.js
- packages/header/stories/header.stories.tsx
- packages/popup-menu/src/popup-menu.tsx
- packages/user-menu/src/user-menu.tsx
- packages/user-menu/stories/user-menu.stories.tsx
Breaking changes: removed a lot.
> feat:usermenu

- .storybook/main.ts
- .storybook/manager-head.html
- .storybook/preview.tsx
- .storybook/styles.scss
- package.json
- packages/core/src/colors.js
- tailwind.config.js
- yarn.lock
This is done with some modification in styling to make sure storybook docs text is readable in darkmode. We could also decide to only add darkmode to the stories, it's up for discussion.
> added darkmode-switch

- packages/user-menu/src/user-menu.tsx
added key for hidden elements.
> Bug in user-menu

- packages/table/src/zebratable.tsx
added aria-hidden caption outside table, och visually hidden caption inside.
> fix: table caption

- .storybook/styles.scss
- packages/core/src/components/radio.js
- packages/radio/src/radio-group.tsx
- packages/radio/src/radio.tsx
- packages/radio/src/styles.ts
- packages/radio/stories/radio-group.stories.tsx
- packages/radio/stories/radio.stories.tsx
BREAKING CHANGE: color is no longer a prop on radiobutton. Sizes no longer include xl
> feat: new radio button

- packages/breadcrumb/src/breadcrumb.tsx
- packages/breadcrumb/stories/breadcrumb.stories.tsx
- packages/core/src/components/breadcrumb.js
New style added for breadcrumb. "separator" and "addSeparator" are removed from props and "color" is added,
> feat: Added breadcrumbs

- packages/core/src/components/button.js
- packages/core/src/components/pagination.js
- packages/core/src/components/zebratable.js
- packages/pagination/src/pagination.tsx
- packages/pagination/src/styles.ts
- packages/table/src/datatable.tsx
- packages/table/src/zebratable.tsx
> fix: tables, button and pagination

- packages/core/src/components/filter.js
- packages/core/src/plugin.js
- packages/filter/CHANGELOG.md
- packages/filter/LICENSE
- packages/filter/README.md
- packages/filter/index.ts
- packages/filter/package.json
- packages/filter/src/filter-item.tsx
- packages/filter/src/filter-label.tsx
- packages/filter/src/filter.tsx
- packages/filter/src/index.ts
- packages/filter/stories/filter.stories.tsx
- packages/filter/tsconfig.json
- packages/forms/src/checkbox/index.ts
- packages/react/package.json
- packages/react/src/index.ts
- yarn.lock
fix: adjustment for user-menu version in react
> feat: Added Filter

- packages/core/src/components/divider.js
- packages/divider/src/divider-section.tsx
- packages/divider/src/divider.tsx
- packages/divider/src/index.ts
- packages/divider/src/styles.ts
- packages/divider/stories/divider-section.stories.tsx
- packages/divider/stories/divider.stories.tsx
fix(divider): prefixed with 'sk'
> feat: added divider section

- packages/core/src/components/header.js
- packages/core/src/components/logo.js
fixed issue with logo shrinking
> fix: header logo styling

- packages/accordion/package.json
- packages/accordion/src/accordion/accordion-item.tsx
- packages/accordion/src/disclosure/disclosure.tsx
- packages/accordion/src/disclosure/styles.ts
- packages/accordion/stories/accordion.stories.tsx
- packages/accordion/stories/disclosure.stories.tsx
- packages/core/src/components/accordion.ts
added new variant, support text, label and leading icon
> feat(accordion): new disclosure variant

- packages/modal/src/modal/modal.tsx
- packages/tabs/src/tabs-button.tsx
fix(modal): Type is now based on actual headless component type
fix(tabs): importing as named module
> fix: broken build

- packages/react/package.json
- packages/react/src/index.ts
Exportera tooltipkomponenten.
Är detta allt som behövs?
> Export tooltip

- packages/forms/package.json
- packages/forms/src/combobox/combobox.tsx
- yarn.lock
cjs support were broken due to @react-hookz/web only supporting esm.
Replaced package with usehooks-ts
> fix(combobox): replaced @react-hookz/web with usehooks-ts

- packages/forms/src/checkbox/checkbox.tsx
- packages/forms/stories/checkbox.stories.tsx
moved classes to label (first element).
updated story with inderterminate example
> fix(checkbox): checkbox rounded corners

- packages/menu-vertical/src/menu-vertical-context.tsx
- packages/menu-vertical/src/menu-vertical.tsx
fix: context refactored to ensure right state being used
fix: removed redundant code (setSubmenufix)
> fix(menu-vertical): menuindex-prop did not work

- packages/theme/src/gui-provider.tsx
To be able to change color scheme with useGui();
```
const {setColorScheme} = useGui();
return <button onClick={() => setColorScheme(ColorSchemeMode.Dark)>Dark mode</button>;
```
> feat: change colorScheme from useGui()

- packages/menu-vertical/src/menu-vertical-item.tsx
- packages/menu-vertical/src/menu-vertical.tsx
- packages/utils/src/assertion.ts
- skipped using component name as comparison
> fix(menu-vertical): broken prod build

- packages/core/src/components/table-autotable.ts
- packages/table/src/table.tsx
the default behaviour of neither table nor auto-table should be affected
> feat: added support to control wrapping border

- packages/ai/src/components/ai-feed/ai-feed-entry.tsx
- packages/ai/src/components/ai-feed/ai-feed.tsx
- packages/ai/src/types/index.ts
- packages/ai/src/types/titles.ts
- packages/ai/stories/ai-feed.stories.tsx
Change titles of message origins.
Hide or show titles depending on origin
> feat: added titles to feed

- packages/ai/src/components/ai-module/ai-module-mobile-menu.tsx
- packages/ai/src/components/ai-module/ai-module-sessions.tsx
- packages/ai/src/components/ai-module/ai-module.tsx
preventing sessions being fethced when not used
> fix: moved session to session history component

- packages/core/src/components/ai/ai-corner-module.ts
https://jira.sundsvall.se/browse/AI-61
> fix(ai): max height on corner module

- packages/core/src/components/ai/ai-feed.ts
preventing text to inherit position from parent with centered text.
> fix(ai): added text left

- packages/table/src/auto-table.tsx
----
Autotable would not rerender when changing headers. And sometimes when it did rerender, it failed to read `undefined` header properties
> fix: header bug causing rendering issues

- packages/button/stories/button-group.stories.tsx
- packages/button/stories/button.stories.tsx
- packages/forms/stories/input.stories.tsx
- packages/forms/stories/text-field.stories.tsx
- packages/icon/src/index.ts
- packages/layout/stories/footer.stories.tsx
- packages/layout/stories/header.stories.tsx
- packages/menubar/stories/menubar.stories.tsx
- packages/popup-menu/stories/popup-menu.stories.tsx
- packages/table/stories/autotable.stories.tsx
- packages/table/stories/table.stories.tsx
- packages/text/stories/text.stories.tsx
- packages/tooltip/stories/tooltip.stories.tsx
> docs: changed Icon import in stories

- packages/pagination/src/pagination.tsx
> fix: minor fixes and screen reader improvements

- packages/accordion/src/disclosure/disclosure.tsx
- packages/core/src/components/accordion.ts
> fix: removed tailwind from the component

- packages/accordion/stories/disclosure.stories.tsx
> fix:  updated icon.

- packages/theme/src/colors.ts
https://jira.sundsvall.se/browse/UF-9513
> fix: color contrast on error and warning

- packages/ai/src/hooks/useChat.ts
Throw error to force stream to stop.
> fix: stop stream on error

- packages/core/src/components/ai/ai-service-module.ts
> fix(ai): move chat on top

- .storybook/main.ts
- packages/core/src/components.ts
- packages/core/src/components/file-upload.ts
- packages/forms/package.json
- packages/forms/src/file-upload/defaults.ts
- packages/forms/src/file-upload/file-upload-area.tsx
- packages/forms/src/file-upload/file-upload-button.tsx
- packages/forms/src/file-upload/file-upload-field.tsx
- packages/forms/src/file-upload/file-upload-list-item-actions.tsx
- packages/forms/src/file-upload/file-upload-list-item-content-category.tsx
- packages/forms/src/file-upload/file-upload-list-item-content-name.tsx
- packages/forms/src/file-upload/file-upload-list-item-content.tsx
- packages/forms/src/file-upload/file-upload-list-item-icon.tsx
- packages/forms/src/file-upload/file-upload-list-item.tsx
- packages/forms/src/file-upload/file-upload-list.tsx
- packages/forms/src/file-upload/hooks.ts
- packages/forms/src/file-upload/index.ts
- packages/forms/src/file-upload/types.ts
- packages/forms/src/file-upload/utils.ts
- packages/forms/src/index.ts
- packages/forms/stories/file-upload/file-upload-area.stories.tsx
- packages/forms/stories/file-upload/file-upload-field.stories.tsx
- packages/forms/stories/file-upload/file-upload-list-item.stories.tsx
- packages/forms/stories/file-upload/file-upload-list.stories.tsx
- packages/forms/stories/file-upload/file-upload.stories.tsx
- packages/utils/src/children.ts
- yarn.lock
> feat(forms): created FileUpload

- packages/searchfield/src/searchfield.tsx
Jira: https://jira.sundsvall.se/browse/UF-11329
> feat: ändrat från primary till tertiary

- packages/core/src/components/pagination.ts
- packages/core/src/components/table.ts
- packages/table/src/auto-table.tsx
- packages/table/stories/autotable.stories.tsx
> fix: allow for pageSizeVariant, synced to new design

- packages/forms/package.json
> Added missing dependency for file-upload

- packages/ai/package.json
- packages/ai/stories/ai-service-module.stories.tsx
- packages/ai/tsconfig.json
- packages/ai/tsconfig.production.json
> fix(ai): type-compilation created dependency-types

- packages/core/src/components/checkbox.ts
- packages/core/src/components/input.ts
- packages/core/src/components/radio.ts
- packages/core/src/components/select.ts
- packages/forms/src/checkbox/checkbox.tsx
- packages/forms/src/input-group/index.tsx
- packages/forms/src/input/input.tsx
- packages/forms/src/radio/radio.tsx
- packages/forms/src/select/index.tsx
- packages/forms/stories/checkbox.stories.tsx
- packages/forms/stories/select.stories.tsx
- packages/forms/stories/text-field.stories.tsx
- packages/forms/stories/textarea.stories.tsx
Jira: https://jira.sundsvall.se/browse/UF-11449
> feat: styling to readonly elements

- Dockerfile
> fix: updated alpine version

- packages/core/src/components/tabs.ts
> uf-14491 fix(tabs): hover effect

- packages/theme/src/gui-provider.tsx
Jira: https://jira.sundsvall.se/browse/UF-14582
> bugfix: systemfärg flashar vid sidbyte

- packages/ai/src/components/ai-corner-module/ai-corner-module-header.tsx
- packages/core/src/components/ai/ai-corner-module.ts
> fix(ai): wrong size on corner module header

- packages/core/src/components/menu-vertical.ts
> uf-14702 fix(menu-vertical): menu vertical item padding

- packages/ai/src/components/ai-feed/ai-feed-entry.tsx
- packages/ai/src/components/markdown-rendered.tsx
- packages/ai/src/services/sanitizer-service.ts
- packages/ai/stories/ai-feed.stories.tsx
- packages/ai/stories/ai-service-module-assistant.stories.tsx
- packages/core/src/components/ai/markdown-rendered.ts
https://jira.sundsvall.se/browse/AI-179
> fix(ai): added code to markdown render

- packages/ai/src/hooks/useChat.ts
- packages/ai/src/services/assistant-service.ts
- packages/ai/src/types/assistant.ts
> feat: Added attached files to useChat-hook

- packages/avatar/src/avatar.tsx
- packages/core/src/components/avatar.ts
- packages/core/src/units.ts
- packages/theme/src/units.ts
> feat: added size xs for avatar

- packages/forms/src/file-upload/file-upload-area.tsx
- packages/forms/src/file-upload/file-upload-button.tsx
- packages/forms/src/file-upload/file-upload-field.tsx
- packages/forms/stories/file-upload/file-upload-area.stories.tsx
- packages/forms/stories/file-upload/file-upload-field.stories.tsx
- packages/forms/stories/file-upload/file-upload.stories.tsx
> fix: better docs for validation and minor refactor

- packages/core/src/components/menubar.ts
- packages/menubar/src/context.ts
- packages/menubar/src/menubar-item.tsx
- packages/menubar/src/menubar.tsx
- packages/menubar/src/use-menubar.ts
> feat: added md and lg sizes to menubar

- packages/core/src/components/badge.ts
[UF-15777](https://jira.sundsvall.se/browse/UF-15777)
> fix(badge): flexible width

- packages/core/src/components/tabs.ts
Jira: https://jira.sundsvall.se/browse/UF-15776
> feat(tabs): removed rounding on devider

- packages/ai/src/hooks/useChat.ts
[AI-293](https://jira.sundsvall.se/browse/AI-293)
> feat(useChat): optional add to history on sendQuery

- packages/ai/src/assistant-store.tsx
- packages/ai/src/hooks/useChat.ts
- packages/ai/src/services/assistant-service.ts
- packages/ai/src/types/assistant.ts
[AI-295](https://jira.sundsvall.se/browse/AI-295)
> feat(services): added option to use apikey

- packages/toasted-notes/src/Message.tsx
[UF-16681](https://jira.sundsvall.se/browse/UF-16681)
> fix: prevent ref to pass to fragment

- packages/core/src/components/file-upload.ts
- packages/forms/src/file-upload/file-upload-list-item-actions.tsx
- packages/forms/src/file-upload/file-upload-list-item-remove-button.tsx
Added aria-label for better screenreading support. Added tooltip to help the users understand the function of the remove button.
Jira: https://jira.sundsvall.se/browse/UF-17210
> feat: aria-label support and new tooltip

- packages/core/src/components/footer.ts
> fix: Footer logo width for ios

- packages/core/src/components/input.ts
- packages/forms/src/input-group/index.tsx
- yarn.lock
Jira: https://jira.sundsvall.se/browse/UF-17261
> fix: input group will now grow as intended

- packages/snackbar/stories/snackbar.stories.tsx
- packages/text-editor/src/text-editor.tsx
- packages/text-editor/src/toolbar.ts
- packages/text-editor/src/tooltip-text.ts
- packages/text-editor/stories/text-editor.stories.tsx
- This PR also includes fix for defaultValue handling.
Jira: https://jira.sundsvall.se/browse/UF-16858
> feat: added custom toolbar option for texteditor

- packages/text-editor/src/index.ts
- packages/text-editor/src/text-editor.tsx
- packages/text-editor/stories/text-editor.stories.tsx
BREAKING CHANGE: DefaultValue prop is removed
> feat: onChange event for plaintext and markup

- packages/text-editor/src/text-editor.tsx
> fix: Updating texteditor value when quillref is created

- packages/ai/src/services/assistant-service.ts
> fix(assistant-service): hash should not be required
